env:
  node: true
  browser: true
  commonjs: true
  es6: true
  mocha: true
extends: 
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars: 
    - off
  vue/component-name-in-template-casing:
    - off 
  vue/name-property-casing: 
    - off
